In [2]:
import math
def basic_sigmoid(x):
    s = 1 / (1+math.exp(-x))
    return s


In [3]:
import numpy as np
x = [1,2,3]
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [4]:
import math
def sigmoid(x):
    s = 1 / (1+np.exp(-x))
    return s


In [5]:
x = np.array([1,2,3,4])
sigmoid(x)


array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [6]:
import math
def sigmoid_derivative(x):
    s = 1 / (1+np.exp(-x))
    ds = s*(1-s)
    return ds


In [7]:
sigmoid_derivative(x)

array([0.19661193, 0.10499359, 0.04517666, 0.01766271])

In [8]:
def image2vector(x):
    s = x.reshape(x.shape[0]*x.shape[1]*x.shape[2],1)
    return s

In [9]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [10]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp,axis = 1, keepdims = True)
    s = x_exp / x_sum
    return s

In [11]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))


softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
